public enum StatusLibrarianMenu {

    ADD_BOOK_IN_WAREHOUSE, REMOVE_BOOK_FROM_WAREHOUSE, PRINT_ALL_ORDERS, PRINT_ALL_COMPLECTED_ORDERS, PRINT_ALL_REQUESTS, PRINT_STALE_BOOKS, PRINT_PROFIT, PRINT_CNT_COMPLECTED_ORDERS, BACK_MAIN_MENU, UNCORRECT_CHOICE
    
}
