package senla.course.enums;

public enum StatusOperationOrder {
    ORDER_NOT_FOUND, CREATE_ORDER, ERROR_CREATE_ORDER, CLOSED_ORDER, CLOSED_ALREADY_ORDER, COMPLECTED_ORDER, COMPLECTED_ALREADY_ORDER, ERROR_COMPLECTED_ORDER, ORDER_COMPLECTED_BEFORE_CLOSE, ORDER_CLOSED_BEFORE_COMPLECTED
}
